### PR TITLE
Add a mkdocs extension to generate the --help output

### PR DESCRIPTION
**Pull request by joerick**
I was getting a bit tired of having to remember to update the --help output in the options docs, so I wrote a mkdocs extension that allows a snippet of python code in the docs that will run when the page is rendered. It's invoked like this:

~~~markdown
```python execute-and-replace
import subprocess

print('```text')
subprocess.run(['cibuildwheel', '--help'], check=True, stderr=subprocess.STDOUT)
print('```')
```
~~~

That is replaced at build time with the --help output from cibuildwheel.

I have a feeling it might be useful elsewhere, too, but I can't think of anything off the top of my head!

### CODE REVIEW

**Comment by joerick** [comment]
See the output here:
https://cibuildwheel--720.org.readthedocs.build/en/720/options/#command-line

**Comment by joerick** [comment]
Super weird error from pip here, when the first Python 3.6 is installed. Does this mean that the CPython 3.6 build environment is the same as the environment that cibuildwheel was installed into? I think so.

I'm guessing that the local dependency isn't a feature that's available in the bundled setuptools with Python 3.6, so that's why it's erroring. Maybe I'll just spin out the mkdocs extension as its own package instead, unless anyone has another idea of how to do local dependencies with setuptools `extras_require`? 

```
Building cp36-macosx_x86_64 wheel
CPython 3.6 macOS x86_64

Installing Python cp36...
  
  + Download https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg to /tmp/Python.pkg
  + sudo installer -pkg /tmp/Python.pkg -target /
  installer: Package name is Python
  installer: Upgrading at base path /
  installer: The upgrade was successful.
  + sudo /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 /Users/runner/work/cibuildwheel/cibuildwheel/cibuildwheel/resources/install_certifi.py
  The directory '/Users/runner/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  The directory '/Users/runner/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting certifi
    Downloading https://files.pythonhosted.org/packages/05/1b/0a0dece0e8aa492a6ec9e4ad2fe366b511558cdc73fd3abc82ba7348e875/certifi-2021.5.30-py2.py3-none-any.whl (145kB)
  Exception:
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2585, in _dep_map
      return self.__dep_map
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2677, in __getattr__
      raise AttributeError(attr)
  AttributeError: _Distribution__dep_map
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2963, in __init__
      super(Requirement, self).__init__(requirement_string)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
      raise InvalidRequirement("Invalid URL: {0}".format(req.url))
  pip._vendor.packaging.requirements.InvalidRequirement: Invalid URL: file:///Users/runner/work/cibuildwheel/cibuildwheel/docs/mkdocs_execute_python_plugin
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
      status = self.run(options, args)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 349, in run
      self._warn_about_conflicts(to_install)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 475, in _warn_about_conflicts
      package_set, _dep_info = check_install_conflicts(to_install)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
      package_set = create_package_set_from_installed()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
      package_set[name] = PackageDetails(dist.version, dist.requires())
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2621, in requires
      dm = self._dep_map
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2587, in _dep_map
      self.__dep_map = self._filter_extras(self._build_dep_map())
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2616, in _build_dep_map
      dm.setdefault(extra, []).extend(parse_requirements(reqs))
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in parse_requirements
      yield Requirement(line)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2965, in __init__
      raise RequirementParseError(str(e))
  pip._vendor.pkg_resources.RequirementParseError: Invalid URL: file:///Users/runner/work/cibuildwheel/cibuildwheel/docs/mkdocs_execute_python_plugin
  You are using pip version 18.1, however version 21.1.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
   -- pip install --upgrade certifi
  Traceback (most recent call last):
    File "/Users/runner/work/cibuildwheel/cibuildwheel/cibuildwheel/resources/install_certifi.py", line 55, in <module>
      main()
    File "/Users/runner/work/cibuildwheel/cibuildwheel/cibuildwheel/resources/install_certifi.py", line 32, in main
      [sys.executable, "-E", "-s", "-m", "pip", "install", "--upgrade", "certifi"]
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.6/bin/python3', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 2.
```

**Comment by henryiii** [comment]
Could you use https://github.com/fralau/mkdocs_macros_plugin (looking at https://chrieke.medium.com/the-best-mkdocs-plugins-and-customizations-fc820eb19759 )? This seems simple enough that it has to have been done before.

**Comment by joerick** [comment]
I did have a quick look, I couldn't find anything that would do this. Maybe that macros plugin would do it, but would still require writing a custom 'pluglet', which seems a bit heavy for something simple like this.

**Pull request merged**
