### PR TITLE
Use tomllib on Python 3.11

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by henryiii** [comment]
Nice, this went in 5 hours ago! https://github.com/python/cpython/tree/main/Lib/tomllib

**Review by joerick — APPROVED** [review]
Great!

**Comment by henryiii** [comment]
FYI, I'm thinking that merging these as soon as the next Python 3.11 alpha is released would be a good idea. For https://github.com/pypa/build/pull/443, it matters, since that is testing against the latest alpha. Here, it doesn't really matter too much (using 3.11 alpha for host seems a little overkill), but might as well do them at the same time, and support the latest alpha, I think.

**Comment by henryiii** [comment]
Waiting on https://github.com/actions/python-versions/pull/155 to merge and deploy.

**Comment by henryiii** [comment]
It's in and up, so don't see a reason to delay this. Let's merge!

**Pull request merged**
