### PR TITLE
Remove macOS build on travis-ci

### PR DESCRIPTION
**Pull request by mayeut**
Leaving macOS results in an "Not enough credits" on travis-ci.com

### CODE REVIEW

**Review by joerick — APPROVED** [review]

**Comment by mayeut** [comment]
@joerick, now that I'm seeing the builds triggered, there's one question left:
should we remove it from the doc or just say it's untested ?

**Comment by pradyunsg** [comment]
My 2 cents: "it's untested because Travis CI doesn't provide us free credits to test it anymore" 🙃

**Comment by joerick** [comment]
heheh! good point. I suppose the 'correct' thing to do would be to remove it from the docs - can we claim that we support it if we don't actually test it? Probably not. Plus, how would we fix it if somebody did report a problem?

Yeah I'd say let's remove it from the docs too.

**Comment by mayeut** [comment]
> Yeah I'd say let's remove it from the docs too.

Done

**Comment by YannickJadoul** [comment]
Do we also want to (temporarily) disable macOS on CircleCI, until they - hopefully - give us the same treatment as joerick/cibuildwheel got?

**Comment by mayeut** [comment]
> Do we also want to (temporarily) disable macOS on CircleCI, until they - hopefully - give us the same treatment as joerick/cibuildwheel got?

That's being handled in #685
I will merge that one & open a new one not to forget it's a temporary state.

**Comment by YannickJadoul** [comment]
> That's being handled in #685

Ugh. Sorry. I need to catch up with my list of unread cibuildwheel emails...

**Review by joerick — APPROVED** [review]

**Pull request merged**
