### PR TITLE
docs: update examples for v4 of `upload-artifact` and `download-artifact` actions

### PR DESCRIPTION
**Pull request by alugowski**
See discussion: https://github.com/pypa/cibuildwheel/issues/1699

### CODE REVIEW

**Comment by alugowski** [comment]
Working workflow using this setup: https://github.com/alugowski/fast_matrix_market/blob/main/.github/workflows/wheels.yml

**Review by joerick — APPROVED** [review]
Looks good to me. Thank you for putting this together. @henryiii I see you're across this so would you mind double-checking this too?

**Comment by henryiii** [comment]
Looks mostly good, just two thoughts:

1. We could make the names generically, using `cibw-${{ github.job }}-${{ strategy.job-index }}`.
2. We could avoid downloading all artifacts, and only download ours using `pattern: cibw-*`.

I think the current PR is probably simplest, as usually (and in this example) there aren't extra artifacts to worry about. We could mention this somewhere, though.

**Review by henryiii — APPROVED** [review]

**Comment by njzjz** [comment]
> We could make the names generically, using `cibw-${{ github.job }}-${{ strategy.job-index }}`.

I tried this, but the name looks too generic when I want to download the wheel for a specific platform.

image

It's hard to know which one is built for Linux.

**Comment by alugowski** [comment]
Would `cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}` and `cibw-sdist` be a good complexity/uniqueness compromise?

I thought just `matrix.os` is enough, but the GH docs use that as the example and I've seen comments complaining, as if they didn't know it was just a suggestion. I think the places where `github.job` would help disambiguate are few, and those folks would know to add it.

Also I just noticed the `examples/` directory that has like 4 workflows that should be updated too. Once a call is made on this I can update those.

**Comment by alugowski** [comment]
>     1. We could make the names generically, using `cibw-${{ github.job }}-${{ strategy.job-index }}`.

Based on feedback above I went with `cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}`, but happy to change.

>     2. We could avoid downloading all artifacts, and only download ours using `pattern: cibw-*`.

Done.

I also updated the example `.yml` files.

**Comment by joerick** [comment]
I like the renamed artifacts with the `cibw` prefix, it also make it clearer what 'merge-multiple' means in the example.

I'll let @henryiii have another look, but LGTM.

**Review by henryiii — APPROVED** [review]
LGTM!

**Comment by alexlancaster** [comment]
The PR seems to be missing an update to the GitHub action in the https://github.com/pypa/cibuildwheel/blob/main/README.md ?

**Comment by alugowski** [comment]
> The PR seems to be missing an update to the GitHub action in the "Example setup " in https://github.com/pypa/cibuildwheel/blob/main/README.md ?

Good catch.

https://github.com/pypa/cibuildwheel/pull/1708

**Pull request merged**
