### PR TITLE
fix: download pipx for action, allow support for M1

### PR DESCRIPTION
**Pull request by henryiii**
Takes an extra second or two, plus it could interfere with the environment a bit if someone activates the same version of Python. But not too bad.

### CODE REVIEW

**Comment by joerick** [comment]
@henryiii, hope it's okay, I pushed a couple commits to get this working. I hope that actions/setup-python wouldn't put spaces in the path! I want to do a quick release to get that Powershell fix in and I thought that we might as well let people try out the new macos-14 runners. We can do the official support with examples/docs in #1700.

**Comment by joerick** [comment]
Erm, actually, on second thoughts maybe that's not a good assumption  given 'Program Files' and all that.

**Comment by henryiii** [comment]
Great, thanks! Had to teach. That's what I was thinking, fixing the powershell plus macOS AS runners would be a good quick patch release.

**Comment by henryiii** [comment]
This won't break Travis, so fine to merge IMO.

**Comment by joerick** [comment]
brill, thanks, releasing now...

**Pull request merged**
