### PR TITLE
Revert "chore: skip PyPy 3.7 7.3.8 updates"

### PR DESCRIPTION
**Pull request by mayeut**
Opening as draft waiting for PyPy 7.3.9

This reverts commit a0341ab06432b7fe7325a4d478fa3025feefea19.

### CODE REVIEW

**Comment by joerick** [comment]
Any idea when this might be ready to go @mayeut ? I've been holding off on a release until the PyPy versions match, but I'm starting to wonder how long that'll last!

**Comment by mayeut** [comment]
> Any idea when this might be ready to go @mayeut ? I've been holding off on a release until the PyPy versions match, but I'm starting to wonder how long that'll last!

No idea when PyPy v7.3.9 will be released. Let's ask @mattip if he has an update on this.

**Comment by mattip** [comment]
It should be out next week. The last blockers were fixed, and it seems the CPython security fixes are final (they had a few glitches) so now I can move the PyPy release forward.

**Comment by joerick** [comment]
PyPy 3.7.9 is out!

**Pull request merged**
