### PR TITLE
Add interactive diagram to the docs

### LINKED ISSUE #468: Ideas for improving the first-run experience
Using the minimal example (https://github.com/joerick/cibuildwheel/blob/master/examples/github-minimal.yml) for GitHub Actions the Ubuntu build fails as it appears to be grabbing the system Python 2.7 instead of the specified Python 3.7:

https://github.com/robbmcleod/cpufeature/runs/1461364117

I tried explicitly using `python3` instead but that fails on Windows. An I assume `pip` is still `pip2` rather than `pip3`. 

I'm trying to learn how to use this tool so I can build the wheels for `numexpr` (which I maintain), as that's going to hold up the  release of `pandas` among other things. So any guidance you can provide here would be greatly appreciated.

### PR DESCRIPTION
**Pull request by joerick**
Fix #468.

This adds a diagram to the docs that summarises what steps cibuildwheel takes when building a wheel. It's interactive, so mousing over a part will show more info. 

One thing I'm not sure about is where to put it in the docs. Currently it's on the 'home' page, it could have its own page. If it had its own page, I could increase the page width a bit too, which might let me increase the font size a bit.

### CODE REVIEW

**Comment by joerick** [comment]
Here it is: https://cibuildwheel--1100.org.readthedocs.build/en/1100/#how-it-works

**Comment by henryiii** [comment]
Would it make sense to have the png image as a no script fallback, since you already have it? (Or does everything fall apart without JS? Do people still browse without JS sometimes?)

**Comment by henryiii** [comment]
This looks fantastic, by the way!

**Comment by henryiii** [comment]
Was going ask about mobile! Noticed it didn’t handle mobile very well when showing it off at PyCon.

**Comment by henryiii** [comment]
The place you press seems small for going to the link on the second press?

**Comment by mayeut** [comment]
this looks very nice !

**Comment by joerick** [comment]
> The place you press seems small for going to the link on the second press?

Yes, good point. I think I'll change the tap behaviour to be: 1st tap = open tooltip. 2nd tap = follow link to docs.

**Comment by joerick** [comment]
> Would it make sense to have the png image as a no script fallback, since you already have it? (Or does everything fall apart without JS? Do people still browse without JS sometimes?)

Indeed our docs do use JS for a few things already. But they still basically work so the noscript fallback is a good idea 👍

**Review by henryiii — APPROVED** [review]
Thought I already did this.

**Comment by henryiii** [comment]
Should we merge before release so it gets in the stable docs?

**Comment by abitrolly** [comment]
Wow. That appeared to be very helpful. How it was made?

**Comment by abitrolly** [comment]
@joerick I wanna reuse that. What are the conditions? :D

**Comment by joerick** [comment]
Same as the rest of the project, BSD license! https://github.com/pypa/cibuildwheel/blob/main/LICENSE

Go for it :)

**Pull request merged**
