### PR TITLE
fix: support --no-isolation with build[uv]

### PR DESCRIPTION
**Pull request by henryiii**
Fixing #1887. I didn't special case chained short flags, like `-xn` or `-nx`, maybe we should?

### CODE REVIEW

**Comment by joerick** [comment]
It looks to me like you're just disabling uv support when `--no-isolation` is passed. Is this a misconfiguration then? As in "you can't specify `build[uv]` and `--no-isolation`, if you need `--no-isolation` you must use `build`"?

**Comment by henryiii** [comment]
We still install everything via uv when `build[uv]` is set. It means “use build and uv”. The problem is that with no isolation, build itself isn’t using uv because it doesn’t install anything or make and environment. That’s why it errors on that flag.

**Comment by joerick** [comment]
Ah, got it. Understood!

**Comment by henryiii** [comment]
If I add a utility for this, it will clash with #1873, so let's do this as a quick fix, and then write a utility later that tries to be smarter for combined flags.

**Comment by henryiii** [comment]
I think we could release after this. Would like to get b3 out!

**Comment by mayeut** [comment]
> I didn't special case chained short flags, like -xn or -nx, maybe we should?

I don't think it's necessary but a note / caution shall be added in the docs then.

**Comment by mayeut** [comment]
> I think we could release after this. Would like to get b3 out!

I cancelled Travis CI to get some time for manylinux. CentOS 7 reached End-Of-Life so mirrors shall be updated on manylinux2014. IMHO, we should wait for the new images before the release.

**Review by mayeut — APPROVED** [review]

**Pull request merged**
