### PR TITLE
Update GitLab support

### LINKED ISSUE #1294: Extend support for more architectures on GitLab
### Description

I really like using `cibuildwheel` on GitHub for building wheels for various architectures, but unfortunately I need to also support projects on GitLab that require wheels for aarch64 and x86-64 architectures on Linux. From what I understand, cibuildwheel can only build wheels for x86-64 architectures on GitLab. I have personally had success building wheels for multiple architectures without cibuildwheel, but I'd like to move away from my current methods. Taken from https://github.com/Mizux/python-native/blob/main/ci/README.md for example, I would run this to create wheels for a Python project to support aarch64:
```bash
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx build -f path/to/Dockerfile --platform linux/arm64 .
```
I originally used https://github.com/dockcross/dockcross to cross-compile my C/C++ bindings for various architectures, however auditwheel indicated they were incompatible similar to what was noted in https://github.com/dockcross/dockcross/issues/475. Unfortunately it seems that running `docker buildx` is the the most foolproof way as of this post to support GitLab builds. I'd like to get away from `docker buildx` since it's quite slow.

As noted in https://github.com/pypa/cibuildwheel/issues/951, it seems GitLab supports macOS runners so functionality could be added to build macOS wheels using that runner, so it could be worth exploring that category at some point.

TL;DR: I really want to build aarch64 wheels on GitLab for Linux and macOS. Any plans to support that?

### PR DESCRIPTION
**Pull request by wbarnha**
Closes #1294

### CODE REVIEW

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---extend-gitlab-qemu-2022-10-07T08-19-37](https://github.com/pypa/cibuildwheel/tree/example-config-test---extend-gitlab-qemu-2022-10-07T08-19-37)
> 
> | Service | Config | Status |
> |---|---|---|
> | gitlab | `examples/gitlab-with-qemu.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---extend-gitlab-qemu-2022-10-07T08-19-37) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by joerick** [comment]
Been a while since we tested the minimals, lets see if there are any gremlins lurking...

> **Examples test run**
> 
> Branch: [example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31](https://github.com/pypa/cibuildwheel/tree/example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31)
> 
> | Service | Config | Status |
> |---|---|---|
> | circleci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/pypa/cibuildwheel/tree/example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31) |
> | gitlab | `examples/gitlab-minimal.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31) |
> | travis-ci | `examples/travis-ci-minimal.yml` | [Build Status](https://travis-ci.org/pypa/cibuildwheel) |
> | appveyor | `examples/appveyor-minimal.yml` | [Build status](https://ci.appveyor.com/project/pypa/cibuildwheel/branch/example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31) |
> | azure-pipelines | `examples/azure-pipelines-minimal.yml` | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31) |
> | github | `examples/github-minimal.yml` | [Build](https://github.com/pypa/cibuildwheel/actions) |
> | cirrus-ci | `examples/cirrus-ci-minimal.yml` | [Cirrus CI](https://cirrus-ci.com/github/pypa/cibuildwheel/example-config-test---extend-gitlab-qemu-2022-10-07T08-25-31) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by wbarnha** [comment]
> Ah, Gitlab supports windows now? Could you add a job to our `.gitlab-ci.yml ` so that we run our tests on that platform too?

Done, not 100% sure if it'll work though.

I'm also waiting to hear back on GitLab for access to macOS runner to find out if my example can build wheels for macOS. Not sure how long that will take so feel free to merge this in and I'll create another MR when I get that working.

**Review by joerick — APPROVED** [review]

**Review by henryiii — APPROVED** [review]

**Comment by joerick** [comment]
Thanks @wbarnha!

**Pull request merged**
