### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by bigcat88**
Add `pillow-heif`

### CODE REVIEW

**Comment by henryiii** [comment]
pre-commit.ci autofix

**Comment by henryiii** [comment]
@joerick could you add me to the AppVeyor instance so I can restart jobs? I'm `HenrySchreiner` there.

**Comment by mayeut** [comment]
@henryiii, I can't give you access but I could restart the job.

**Comment by henryiii** [comment]
Thanks!

**Comment by joerick** [comment]
> @joerick could you add me to the AppVeyor instance so I can restart jobs? I'm `HenrySchreiner` there.

done!

**Pull request merged**
