### PR TITLE
Create a bug report issue template

### PR DESCRIPTION
**Pull request by joerick**

### CODE REVIEW

**Comment by joerick** [comment]
I'm wondering if an issue template might be useful for us. I sometimes find myself asking reporters for a link to their config or a build log, so putting that in the template might help?

**Comment by henryiii** [comment]
I would use issue forms over templates, they are a bit nicer and can be enforced to a degree. See https://github.com/pypa/packaging-problems/issues/new?assignees=&labels=&template=packaging_tutorial.yml&title=Trouble+with+a+packaging+tutorial or pip for example.

**Comment by joerick** [comment]
Huh, I didn't know about issue forms. I suppose they're still in beta so Github didn't recommend them to me. But yeah, they seem potentially nicer. I'll look at using them instead...

**Comment by henryiii** [comment]
Maybe you could add an optional spot for raw code, like a traceback or code sample? Either way, fine with me.

**Comment by joerick** [comment]
Cool, thanks for taking a look. Let's see how we go - I err towards less structure I think.

**Pull request merged**
