### PR TITLE
docs for native arm building on circleci

### LINKED ISSUE #1241: CircleCI + native aarch64 linux buils work, how to document this?
Here is how we did it, as inspired by @minrk (their setup is at https://github.com/zeromq/pyzmq/pull/1743 )

https://github.com/common-workflow-language/schema_salad/pull/579/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R15

### PR DESCRIPTION
**Pull request by minrk**
- add note in docs that pyzmq uses both github and circleci, and that it includes native linux arm builds on circle
- add linux-aarch64-wheels job to circleci-minimal example

closes #1241

### CODE REVIEW

**Comment by joerick** [comment]
Brilliant, thank you @minrk! This was next on my todo list :). This is another great resource for those building aarch64, alongside the new Cirrus CI support.

**Review by joerick — COMMENTED** [review]
Given CircleCI's slightly unusual docker support, would you mind configuring our CI to run the tests in `.circleci/config.yml`? Given your success with zmq already, I don't expect any issues, but I think it would be prudent.

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---circle-aarch64-2022-10-12T08-10-50](https://github.com/pypa/cibuildwheel/tree/example-config-test---circle-aarch64-2022-10-12T08-10-50)
> 
> | Service | Config | Status |
> |---|---|---|
> | circleci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/pypa/cibuildwheel/tree/example-config-test---circle-aarch64-2022-10-12T08-10-50) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by minrk** [comment]
added circleci linux-aarch64 job

**Review by joerick — APPROVED** [review]

**Pull request merged**
