### PR TITLE
Debug Appveyor failures

### PR DESCRIPTION
**Pull request by joerick**

### CODE REVIEW

**Comment by mayeut** [comment]
I think it might be related to https://github.com/pypa/virtualenv/issues/2203 / https://github.com/pypa/virtualenv/pull/2256 as I can locally reproduce the issue / fix it / reproduce it by messing with virtualenv cache.
It been solved in virtualenv 20.11.2, bump the test to this one to see if it works.

**Comment by mayeut** [comment]
Seems good: https://ci.appveyor.com/project/joerick/cibuildwheel/builds/42113260/job/1nhf54nmlvnuon88

**Comment by henryiii** [comment]
One of them timed out, otherwise fine? (wasn't really following what was wrong, though)

**Comment by joerick** [comment]
Awesome, thank you @mayeut ! That would have taken me a lot longer to figure out! Yes @henryiii I think the timeout is unrelated.

**Comment by joerick** [comment]
The linux timeout is also problematic, I'll see if I can request an extension with Appveyor.

**Comment by joerick** [comment]
Appveyor increased the build time, so we should be good to go here!

**Comment by mayeut** [comment]
cleaned up history & rebased on main.

**Comment by mayeut** [comment]
there's the same issue with pip on travis-ci windows, will fix that also

**Comment by mayeut** [comment]
only the emulation test remains and this one is a bit flaky as mentioned in #882 so merging this.

**Pull request merged**
