### PR TITLE
ci: run pytest directly

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by henryiii** [comment]
I'm not seeing this anymore with `0.26.0`, I think it was only on `0.26.0a6`.

**Comment by hoodmane** [comment]
Weird.

**Comment by mayeut** [comment]
I'm still seeing the issue locally and on GHA macOS-14.

**Comment by hoodmane** [comment]
Weird weird weird.

**Comment by mayeut** [comment]
I commented directly in https://github.com/pyodide/pyodide/issues/4802#issuecomment-2136226318 with my findings.

**Comment by mayeut** [comment]
I'll close this pull request now that the problem has been identified in pyodide.

**Pull request closed without merging**
