### PR TITLE
feat: support config-settings

### PR DESCRIPTION
**Pull request by henryiii**
Addresses https://github.com/pypa/cibuildwheel/issues/1227. Don't have much for tests yet, open to ideas.

### CODE REVIEW

**Comment by joerick** [comment]
This looks good to me! Only thing I'm wondering about is, since the values use quotes and shlex.split, what happens with a config like this:

```toml
[tool.cibuildwheel.config-settings]
example = "a string with \"some quotes\" in it"
```

I don't know if that works, but... maybe that's an evil/unrealistic input, so if it's awkward to support we could just raise an error when a config-settings value has a double-quote in it (and request the user raise an issue on the tracker).

**Comment by henryiii** [comment]
Would it be better to use `shlex.quote`? `_inner_fmt` could provide the quoted value too, as `quoted_v` or something.

**Comment by joerick** [comment]
Yeah I think shlex.quote would work better. I think that shlex.split and shlex.quote should roundtrip perfectly.

**Review by joerick — APPROVED** [review]
Oh nice. I hadn't realised the shlex.quote fix would apply to environment too.

**Pull request merged**
